---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include release specific variables
  include_vars: "{{ loop_var }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: "../vars"
      skip: "yes"
  loop_control:
    loop_var: "loop_var"
  tags: php

- name: include release specific tasks
  include_tasks: "{{ loop_var }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: "."
      skip: "yes"
  loop_control:
    loop_var: "loop_var"
  tags: php

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  with_items:
    - { dest: "/usr/local/share/composer" }
  tags: php

- name: copy templates
  template:
    src: "./templates{{ item.dest }}.j2"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - { dest: "/etc/profile.d/composer.sh" }
  tags: php

- name: install composer globally (snapshot channel)
  shell: |
    curl -skL https://getcomposer.org/installer | php -- \
      --snapshot \
      --install-dir=/usr/local/bin \
      --filename=composer
  args:
    creates: "/usr/local/bin/composer"
    warn: false
  tags: php

- name: composer self-update (stable channel)
  command: su -l -s /bin/bash -c 'composer self-update --stable --no-interaction'
  args:
    warn: false
  register: composer_self_update_result
  changed_when: "'You are already using composer' not in composer_self_update_result.stderr"
  ignore_errors: yes
  tags: php

- name: composer global init
  command: su -l -s /bin/bash -c 'composer global init --no-interaction'
  args:
    creates: "/usr/local/share/composer/composer.json"
    warn: false
  register: composer_global_init_result
  changed_when: composer_global_init_result.rc != 0
  tags: php

- name: composer global require
  command: su -l -s /bin/bash -c 'composer global {{ item.state }} {{ item.name }} --no-interaction'
  args:
    warn: false
  with_items:
    - { state: 'require', name: 'hirak/prestissimo:@stable' }
    - { state: 'require', name: 'consolidation/cgr:@stable' }
  register: composer_global_require_result
  changed_when: composer_global_require_result.rc != 0
  tags: php

- name: composer global update
  command: su -l -s /bin/bash -c 'composer global update'
  args:
    warn: false
  register: composer_global_update_result
  changed_when: composer_global_update_result.rc != 0
  tags: php

- name: cgr require
  command: su -l -s /bin/bash -c 'cgr {{ item.state }} {{ item.name }}'
  args:
    warn: false
  with_items: "{{ _cgr }}"
  register: cgr_require_result
  changed_when: cgr_require_result.rc != 0
  tags: php

- name: cgr update
  command: su -l -s /bin/bash -c 'cgr update'
  args:
    warn: false
  register: cgr_update_result
  changed_when: "'Package operations:' in cgr_update_result.stderr"
  tags: php
